[theme]
# Primary accent color for interactive elements.
primaryColor = "#262920"

# Background color for the main content area.
backgroundColor ="#f4e9d1"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor ="#f4e9d1"

# Color used for almost all text.
textColor = "#262920"